on: push

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: mkdir build
      - run: dart pub get
      - run: dart compile exe bin/main.dart -v -o "build/BrainJuice.exe"
      - uses: actions/upload-artifact@v1
        with:
          name: Windows
          path: build
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: mkdir build
      - run: dart pub get
      - run: dart compile exe bin/main.dart -v -o "build/BrainJuice"
      - uses: actions/upload-artifact@v1
        with:
          name: Linux
          path: build
  build_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: mkdir build
      - run: dart pub get
      - run: dart compile exe bin/main.dart -v -o "build/BrainJuice"
      - uses: actions/upload-artifact@v1
        with:
          name: MacOS
          path: build